name       : gnome-online-accounts
version    : 3.46.0
release    : 40
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-online-accounts.git : 3.46.0
homepage   : https://wiki.gnome.org/Projects/GnomeOnlineAccounts
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts
description: |
    GNOME Online Accounts is a single sign-on framework for GNOME. It aims to provide a way for users to setup online accounts to be used by the core system and core applications only.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-1.0)
    - pkgconfig(webkit2gtk-4.1)
    - docbook-xml
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build -j4
install    : |
    %ninja_install
