name       : gnome-online-accounts
version    : 3.22.5
release    : 18
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-online-accounts/3.22/gnome-online-accounts-3.22.5.tar.xz : a8a4894ea5c6ba4508f8fec539287f2ebaf2c9bcf4426463b6724ca58b9d8982
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
    - pkgconfig(gobject-introspection-1.0)
    - docbook-xml
    - vala
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
