name        : gnome-online-accounts
version     : 3.18.1
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-online-accounts/3.18/gnome-online-accounts-3.18.1.tar.xz : 6cde6b0966936c533447da8a23cade74de33b7dd6a801e1f8198b890e776c2c2
license     :
    - GPLv2+
summary     : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps   :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
description : |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --libexecdir=/usr/lib/gnome-online-accounts \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
