name       : gnome-online-accounts
version    : 3.24.3
release    : 23
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-online-accounts/3.24/gnome-online-accounts-3.24.3.tar.xz : 252e58eb953032f84731724ff2e8c8afb403ca803bd35382eabcfeee9c703854
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - docbook-xml
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
