name        : gnome-online-accounts
version     : 3.16.4
release     : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-online-accounts/3.16/gnome-online-accounts-3.16.4.tar.xz : a1bb97b36ef3678323f2c73fcdb79c26f1a129521d07e80b66bee039881dc087
license     :
    - GPLv2+
summary     : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps   :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
description : |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --libexecdir=/usr/lib/gnome-online-accounts \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
