name       : gnome-online-accounts
version    : 3.28.0
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-online-accounts/3.28/gnome-online-accounts-3.28.0.tar.xz : 87bc4ef307604f1ce4f09f6e5c9996ef8d37ca5e0a3bf76f6b27d71844adb40c
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(com_err)
    - pkgconfig(gcr-3)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - docbook-xml
    - vala
setup      : |
    %configure --disable-static --enable-kerberos --enable-todoist
build      : |
    %make
install    : |
    %make_install
