name       : gnome-online-accounts
version    : 3.38.0
release    : 33
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-online-accounts.git : 3.38.0
license    : GPL-2.0-or-later
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(gcr-3)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(krb5)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(webkit2gtk-4.0)
    - docbook-xml
    - vala
setup      : |
    %meson_configure -Dlastfm=true
build      : |
    %ninja_build
install    : |
    %ninja_install
