name       : gnome-online-accounts
version    : 3.22.4
release    : 16
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-online-accounts/3.22/gnome-online-accounts-3.22.4.tar.xz : 5415d6dd7babf1371f79ba4f6c031003c7d991aaaa784d58f42fd9b4792b09b9
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
    - pkgconfig(gobject-introspection-1.0)
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
