name       : gnome-online-accounts
version    : 3.20.2
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-online-accounts/3.20/gnome-online-accounts-3.20.2.tar.xz : 4b555d9d2587d49148929e836ff02d5dda80c4138f69036fa214b71383cdc1dd
license    :
    - GPL-2.0
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
    - pkgconfig(gobject-introspection-1.0)
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
