name       : gnome-online-accounts
version    : 3.20.4
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-online-accounts/3.20/gnome-online-accounts-3.20.4.tar.xz : d5ca22404d1ef671a99f6b76ee09d4d4377ce9c86748fd1577b0a95a5129fa3f
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
    - pkgconfig(gobject-introspection-1.0)
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
