name        : gnome-online-accounts
version     : 3.18.3
release     : 11
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-online-accounts/3.18/gnome-online-accounts-3.18.3.tar.xz : bfb983831af8b1fbd81b70befda7683a38f86ca4cc911f763ae31207306e3827
license     :
    - GPLv2+
summary     : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps   :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
    - pkgconfig(gobject-introspection-1.0)
description : |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --libexecdir=/usr/lib/gnome-online-accounts \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
