name       : gnome-online-accounts
version    : 3.26.1
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-online-accounts/3.26/gnome-online-accounts-3.26.1.tar.xz : 603c110405cb89a01497a69967f10e3f3f36add3dc175b062ec4c5ed4485621b
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access
    the user's online accounts.
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - docbook-xml
    - vala
setup      : |
    %configure --disable-static --enable-todoist
build      : |
    %make
install    : |
    %make_install
