name       : gnome-online-accounts
version    : 3.24.0
release    : 20
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-online-accounts/3.24/gnome-online-accounts-3.24.0.tar.xz : 9e2f780e061641dfd692cc82269b0cac6cce73c74ce2d8a0a5e80889ed07c17b
license    : GPL-2.0
component  : desktop.gnome.core
summary    : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
description: |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - docbook-xml
    - vala
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
