name        : gnome-online-accounts
version     : 3.18.4
release     : 12
source     :
    - https://download.gnome.org/sources/gnome-online-accounts/3.18/gnome-online-accounts-3.18.4.tar.xz : 9f23460aa6b1d8a63a8f3e979cba791cc88b5e07116f07da59fdcea09d79c74d
license     :
    - GPLv2+
summary     : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps   :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
    - pkgconfig(gobject-introspection-1.0)
description : |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --libexecdir=/usr/lib/gnome-online-accounts \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
