name        : gnome-online-accounts
version     : 3.18.2
release     : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-online-accounts/3.18/gnome-online-accounts-3.18.2.tar.xz : ed312efddb83aef88546d34d03120bbbf4d2ba9b30401bab00230e79c89583d6
license     :
    - GPLv2+
summary     : The GNOME Online Accounts package contains a framework used to access the user's online accounts.
builddeps   :
    - pkgconfig(telepathy-glib)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - pkgconfig(libsecret-1)
description : |
    The GNOME Online Accounts package contains a framework used to access the user's online accounts.
setup      : |
    %configure --disable-static \
               --libexecdir=/usr/lib/gnome-online-accounts \
               --disable-documentation
build      : |
    %make
install    : |
    %make_install
